'use server';

/**
 * @fileOverview This file defines a Genkit flow for summarizing text input.
 *
 * The flow takes text as input and returns a concise summary generated by AI.
 *
 * @exports {
 *   summarizeTextFromInput: The main function to trigger the summarization flow.
 *   SummarizeTextFromInputInput: The input type for the summarizeTextFromInput function.
 *   SummarizeTextFromInputOutput: The output type for the summarizeTextFromInput function.
 * }
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for the summarizeTextFromInput flow.
 */
const SummarizeTextFromInputInputSchema = z.object({
  text: z.string().describe('The text to summarize.'),
});
export type SummarizeTextFromInputInput = z.infer<typeof SummarizeTextFromInputInputSchema>;

/**
 * Output schema for the summarizeTextFromInput flow.
 */
const SummarizeTextFromInputOutputSchema = z.object({
  summary: z.string().describe('The concise summary of the input text.'),
});
export type SummarizeTextFromInputOutput = z.infer<typeof SummarizeTextFromInputOutputSchema>;

/**
 * Main function to trigger the text summarization flow.
 * @param input - The input text to summarize.
 * @returns A promise that resolves to the summarized text.
 */
export async function summarizeTextFromInput(input: SummarizeTextFromInputInput): Promise<SummarizeTextFromInputOutput> {
  return summarizeTextFromInputFlow(input);
}

/**
 * Prompt definition for summarizing the input text.
 */
const summarizeTextPrompt = ai.definePrompt({
  name: 'summarizeTextPrompt',
  input: {schema: SummarizeTextFromInputInputSchema},
  output: {schema: SummarizeTextFromInputOutputSchema},
  prompt: `Summarize the following text in a concise manner:\n\n{{text}}`,
});

/**
 * Genkit flow definition for summarizing text from input.
 */
const summarizeTextFromInputFlow = ai.defineFlow(
  {
    name: 'summarizeTextFromInputFlow',
    inputSchema: SummarizeTextFromInputInputSchema,
    outputSchema: SummarizeTextFromInputOutputSchema,
  },
  async input => {
    const {output} = await summarizeTextPrompt(input);
    return output!;
  }
);
